---
name: "Segment Editor"
guid: "ace21d44-a4e5-4a85-ae75-acd2e24a9574"
version: "1.0.0.0"
targetAbi: "10.12.0.0"
framework: "net10.0"
releaseChannel: "unstable"
overview: "Segment editing UI embedded as a plugin page"
description: "Packages the Segment Editor web app (built from intro-skipper/segment-editor) as a Jellyfin server plugin"
category: "MoviesAndShows"
owner: "Intro Skipper"
artifacts:
- "SegmentEditorPlugin.dll"
changelog: "- See the full changelog at [GitHub](https://github.com/intro-skipper/segment-editor-plugin/blob/master/CHANGELOG.md)"
